'use client';

import { useState, useRef, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import PageHeader from '../../../components/PageHeader';
import { useAuth } from '../../../contexts/AuthContext';

const SKILL_SUGGESTIONS = ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Python', 'SQL', 'Django', 'Machine Learning', 'TensorFlow', 'Docker', 'AWS', 'Figma', 'Java', 'Spring Boot', 'GraphQL'];

interface WorkEntry { company: string; title: string; startDate: string; endDate: string; description: string; }

function generateCVHtml(data: {
  name: string; email: string; phone: string; address: string; idNumber: string;
  summary: string; skills: string[]; languages: string[];
  experience: string; sector: string;
  work: WorkEntry[]; education: { degree: string; institution: string; year: string };
}) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/>
<title>${data.name} — CV</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',Arial,sans-serif;background:#f9fafb;color:#1f2937}
.wrap{max-width:800px;margin:2rem auto;background:#fff;border-radius:12px;box-shadow:0 4px 24px rgba(0,0,0,.1);overflow:hidden}
.hdr{background:linear-gradient(135deg,#0a1f5c,#2563eb);padding:2.5rem 2rem;color:#fff}
.hdr h1{font-size:2rem;font-weight:800;letter-spacing:-.02em}
.hdr p{margin-top:.35rem;opacity:.75;font-size:.95rem}
.body{padding:2rem}
.sec{margin-bottom:1.75rem}
.sec-title{font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:#2563eb;border-bottom:2px solid #dbeafe;padding-bottom:.4rem;margin-bottom:1rem}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}
.item label{font-size:.75rem;color:#6b7280;font-weight:600}
.item p{font-size:.95rem;color:#111827;margin-top:.15rem}
.pills{display:flex;flex-wrap:wrap;gap:.5rem}
.pill{background:#eff6ff;color:#1d4ed8;border-radius:9999px;padding:.3rem .9rem;font-size:.82rem;font-weight:600}
.pill.lang{background:#f0fdf4;color:#065f46}
.badge{display:inline-block;background:#f3f4f6;color:#374151;border-radius:9999px;padding:.35rem 1rem;font-size:.85rem;font-weight:600}
.work-entry{padding:.75rem;background:#f9fafb;border-radius:8px;margin-bottom:.75rem;border-left:3px solid #2563eb}
.work-entry h4{font-size:.95rem;font-weight:700;color:#111827}
.work-entry .meta{font-size:.8rem;color:#6b7280;margin:.25rem 0}
.work-entry p{font-size:.88rem;color:#374151;line-height:1.6}
.footer{text-align:center;padding:1rem;font-size:.75rem;color:#9ca3af;border-top:1px solid #f3f4f6}
</style></head><body>
<div class="wrap">
  <div class="hdr"><h1>${data.name}</h1><p>${data.experience} &bull; ${data.sector}</p></div>
  <div class="body">
    <div class="sec">
      <div class="sec-title">Personal Information</div>
      <div class="grid2">
        <div class="item"><label>Full Name</label><p>${data.name}</p></div>
        <div class="item"><label>ID Number</label><p>${data.idNumber}</p></div>
        <div class="item"><label>Email</label><p>${data.email}</p></div>
        <div class="item"><label>Phone</label><p>${data.phone}</p></div>
        ${data.address ? `<div class="item" style="grid-column:1/-1"><label>Address</label><p>${data.address}</p></div>` : ''}
      </div>
    </div>
    ${data.summary ? `<div class="sec"><div class="sec-title">Professional Summary</div><p style="color:#374151;line-height:1.7;font-size:.95rem">${data.summary}</p></div>` : ''}
    ${data.work.some(w => w.company) ? `<div class="sec"><div class="sec-title">Work Experience</div>${data.work.filter(w=>w.company).map(w=>`<div class="work-entry"><h4>${w.title}</h4><div class="meta">${w.company} &bull; ${w.startDate}${w.endDate ? ' – '+w.endDate : ' – Present'}</div>${w.description?`<p>${w.description}</p>`:''}</div>`).join('')}</div>` : ''}
    ${data.education.degree ? `<div class="sec"><div class="sec-title">Education</div><div class="work-entry"><h4>${data.education.degree}</h4><div class="meta">${data.education.institution}${data.education.year?' &bull; '+data.education.year:''}</div></div></div>` : ''}
    ${data.skills.length ? `<div class="sec"><div class="sec-title">Skills</div><div class="pills">${data.skills.map(s=>`<span class="pill">${s}</span>`).join('')}</div></div>` : ''}
    ${data.languages.length ? `<div class="sec"><div class="sec-title">Languages</div><div class="pills">${data.languages.map(l=>`<span class="pill lang">${l}</span>`).join('')}</div></div>` : ''}
    <div class="sec"><div class="sec-title">Experience Level</div><span class="badge">${data.experience}</span></div>
  </div>
  <div class="footer">Generated by TalentMap &bull; ${new Date().toLocaleDateString('en-GB')}</div>
</div></body></html>`;
}

export default function CandidateUpload() {
  const { user } = useAuth();
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [mode, setMode] = useState<'upload' | 'template'>('upload');
  const [dragging, setDragging] = useState(false);
  const [uploadedFiles, setUploadedFiles] = useState<{ name: string; size: string; status: 'done' | 'processing' }[]>([]);
  const [saved, setSaved] = useState(false);

  // Template form state
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [summary, setSummary] = useState('');
  const [experience, setExperience] = useState('Mid-Level');
  const [sector, setSector] = useState('Technology');
  const [skills, setSkills] = useState<string[]>([]);
  const [skillInput, setSkillInput] = useState('');
  const [languages, setLanguages] = useState<string[]>([]);
  const [langInput, setLangInput] = useState('');
  const [work, setWork] = useState<WorkEntry[]>([{ company: '', title: '', startDate: '', endDate: '', description: '' }]);
  const [education, setEducation] = useState({ degree: '', institution: '', year: '' });

  useEffect(() => {
    if (!user || user.role !== 'candidate') { router.push('/login'); return; }
    setName(user.name);
    setEmail(user.email);
  }, [user, router]);

  if (!user || user.role !== 'candidate') return null;

  function formatBytes(b: number) {
    if (b < 1024) return b + ' B';
    if (b < 1024 * 1024) return (b / 1024).toFixed(1) + ' KB';
    return (b / (1024 * 1024)).toFixed(1) + ' MB';
  }

  function handleFiles(files: FileList) {
    const arr = Array.from(files);
    const newFiles = arr.map(f => ({ name: f.name, size: formatBytes(f.size), status: 'processing' as const }));
    setUploadedFiles(prev => [...prev, ...newFiles]);
    newFiles.forEach((_, i) => {
      setTimeout(() => {
        setUploadedFiles(prev => prev.map((f, fi) => fi === uploadedFiles.length + i ? { ...f, status: 'done' } : f));
      }, 1400 + i * 500);
    });
  }

  function addSkill(sk: string) {
    const s = sk.trim();
    if (s && !skills.includes(s)) setSkills(prev => [...prev, s]);
    setSkillInput('');
  }

  function addLang(l: string) {
    const s = l.trim();
    if (s && !languages.includes(s)) setLanguages(prev => [...prev, s]);
    setLangInput('');
  }

  function updateWork(i: number, field: keyof WorkEntry, val: string) {
    setWork(prev => prev.map((w, wi) => wi === i ? { ...w, [field]: val } : w));
  }

  function handleSaveDownload() {
    const html = generateCVHtml({ name, email, phone, address, idNumber: user?.idNumber ?? '', summary, skills, languages, experience, sector, work, education });
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${name.replace(/\s+/g, '_')}_CV.html`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function handleSave() {
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  }

  const inputStyle: React.CSSProperties = {
    width: '100%', padding: '0.6rem 0.9rem', border: '1.5px solid #e5e7eb',
    borderRadius: '8px', fontSize: '0.9rem', color: '#111827', background: 'white',
    fontFamily: 'inherit',
  };
  const labelStyle: React.CSSProperties = { display: 'block', fontSize: '0.8rem', fontWeight: 600, color: '#374151', marginBottom: '0.4rem' };

  return (
    <main style={{ minHeight: '100vh', background: '#f9fafb' }}>
      <div style={{ position: 'relative' }}>
        <PageHeader title="TalentMap" subtitle="Candidate Portal" />
      </div>

      <div className="container" style={{ maxWidth: '860px', padding: '2rem 1.5rem' }}>
        <Link href="/candidate" style={{ fontSize: '0.875rem', color: '#6b7280', display: 'inline-flex', alignItems: 'center', gap: '0.25rem', marginBottom: '1.25rem' }}>
          ← Back to My Profile
        </Link>
        <h1 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#111827', marginBottom: '0.35rem' }}>Upload / Update CV</h1>
        <p style={{ color: '#6b7280', marginBottom: '1.5rem' }}>Upload a file or fill in the template below.</p>

        {/* Mode tabs */}
        <div style={{ display: 'flex', gap: '0', marginBottom: '1.75rem', border: '1.5px solid #e5e7eb', borderRadius: '10px', overflow: 'hidden', width: 'fit-content' }}>
          {(['upload', 'template'] as const).map(m => (
            <button key={m} onClick={() => setMode(m)} style={{
              padding: '0.6rem 1.5rem', fontSize: '0.9rem', fontWeight: 600, cursor: 'pointer', border: 'none',
              background: mode === m ? '#2563eb' : 'white',
              color: mode === m ? 'white' : '#6b7280',
              transition: 'all 0.15s',
            }}>
              {m === 'upload' ? '📁 Upload File' : '✏️ Fill Template'}
            </button>
          ))}
        </div>

        {mode === 'upload' && (
          <div>
            <div
              className="card"
              onDragOver={e => { e.preventDefault(); setDragging(true); }}
              onDragLeave={() => setDragging(false)}
              onDrop={e => { e.preventDefault(); setDragging(false); handleFiles(e.dataTransfer.files); }}
              onClick={() => fileInputRef.current?.click()}
              style={{
                border: `2px dashed ${dragging ? '#2563eb' : '#d1d5db'}`,
                background: dragging ? '#eff6ff' : 'white',
                borderRadius: '14px', padding: '3rem 2rem', textAlign: 'center', cursor: 'pointer',
                transition: 'all 0.2s', marginBottom: '1.5rem',
              }}
            >
              <input ref={fileInputRef} type="file" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png"
                style={{ display: 'none' }} onChange={e => e.target.files && handleFiles(e.target.files)} />
              <div style={{ fontSize: '3rem', marginBottom: '0.75rem' }}>📂</div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#111827', marginBottom: '0.4rem' }}>Drop your CV here or click to browse</h3>
              <p style={{ color: '#6b7280', fontSize: '0.875rem', marginBottom: '1.25rem' }}>PDF, Word (.docx), JPG, PNG</p>
              <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', flexWrap: 'wrap', marginBottom: '1.25rem' }}>
                {['PDF', 'DOCX', 'DOC', 'JPG', 'PNG'].map(ext => (
                  <span key={ext} style={{ padding: '0.2rem 0.7rem', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: 600, background: '#f3f4f6', color: '#374151' }}>{ext}</span>
                ))}
              </div>
              <button className="btn-primary" onClick={e => { e.stopPropagation(); fileInputRef.current?.click(); }}>Choose File</button>
            </div>
            {uploadedFiles.length > 0 && (
              <div className="card">
                <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1rem' }}>Uploaded Files</h2>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                  {uploadedFiles.map((f, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '1rem', padding: '0.75rem', background: '#f9fafb', borderRadius: '8px' }}>
                      <span style={{ fontSize: '1.4rem' }}>{f.name.endsWith('.pdf') ? '📄' : f.name.match(/\.(jpg|jpeg|png)$/i) ? '🖼️' : '📝'}</span>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontWeight: 600, fontSize: '0.875rem', color: '#111827' }}>{f.name}</div>
                        <div style={{ fontSize: '0.75rem', color: '#9ca3af' }}>{f.size}</div>
                      </div>
                      {f.status === 'processing'
                        ? <span style={{ color: '#f59e0b', fontSize: '0.85rem' }}>⟳ Processing…</span>
                        : <span style={{ color: '#10b981', fontSize: '0.85rem' }}>✓ Done</span>
                      }
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {mode === 'template' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {/* Personal Info */}
            <div className="card">
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1.25rem' }}>Personal Information</h2>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '1rem' }}>
                {[
                  { label: 'Full Name', val: name, set: setName, placeholder: 'Your full name' },
                  { label: 'Email', val: email, set: setEmail, placeholder: 'email@example.com' },
                  { label: 'Phone', val: phone, set: setPhone, placeholder: '+212 6 XX XX XX XX' },
                  { label: 'Address', val: address, set: setAddress, placeholder: 'City, Country' },
                ].map(({ label, val, set, placeholder }) => (
                  <div key={label}>
                    <label style={labelStyle}>{label}</label>
                    <input value={val} onChange={e => set(e.target.value)} placeholder={placeholder} style={inputStyle} />
                  </div>
                ))}
                <div>
                  <label style={labelStyle}>ID Number</label>
                  <input value={user.idNumber} readOnly style={{ ...inputStyle, background: '#f3f4f6', color: '#6b7280' }} />
                </div>
              </div>
            </div>

            {/* Summary */}
            <div className="card">
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1.25rem' }}>Professional Summary</h2>
              <textarea value={summary} onChange={e => setSummary(e.target.value)}
                placeholder="Brief description of your professional background and goals..."
                rows={4} style={{ ...inputStyle, resize: 'vertical' }} />
            </div>

            {/* Experience + Sector */}
            <div className="card">
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1.25rem' }}>Experience & Sector</h2>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div>
                  <label style={labelStyle}>Experience Level</label>
                  <select value={experience} onChange={e => setExperience(e.target.value)} style={inputStyle}>
                    {['Entry-Level', 'Junior', 'Mid-Level', 'Senior', 'Lead', 'Manager'].map(l => <option key={l}>{l}</option>)}
                  </select>
                </div>
                <div>
                  <label style={labelStyle}>Sector</label>
                  <select value={sector} onChange={e => setSector(e.target.value)} style={inputStyle}>
                    {['Technology', 'Data Science', 'Finance', 'Healthcare', 'Marketing', 'Design', 'Operations', 'Other'].map(s => <option key={s}>{s}</option>)}
                  </select>
                </div>
              </div>
            </div>

            {/* Work Experience */}
            <div className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
                <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827' }}>Work Experience</h2>
                {work.length < 3 && (
                  <button onClick={() => setWork(p => [...p, { company: '', title: '', startDate: '', endDate: '', description: '' }])}
                    style={{ fontSize: '0.8rem', color: '#2563eb', fontWeight: 600, background: 'none', border: 'none', cursor: 'pointer' }}>
                    + Add Entry
                  </button>
                )}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                {work.map((w, i) => (
                  <div key={i} style={{ padding: '1rem', background: '#f9fafb', borderRadius: '10px', borderLeft: '3px solid #2563eb' }}>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '0.75rem', marginBottom: '0.75rem' }}>
                      <div><label style={labelStyle}>Company</label><input value={w.company} onChange={e => updateWork(i, 'company', e.target.value)} placeholder="Company name" style={inputStyle} /></div>
                      <div><label style={labelStyle}>Job Title</label><input value={w.title} onChange={e => updateWork(i, 'title', e.target.value)} placeholder="Your role" style={inputStyle} /></div>
                      <div><label style={labelStyle}>Start Date</label><input value={w.startDate} onChange={e => updateWork(i, 'startDate', e.target.value)} placeholder="Jan 2022" style={inputStyle} /></div>
                      <div><label style={labelStyle}>End Date</label><input value={w.endDate} onChange={e => updateWork(i, 'endDate', e.target.value)} placeholder="Present" style={inputStyle} /></div>
                    </div>
                    <div><label style={labelStyle}>Description</label><textarea value={w.description} onChange={e => updateWork(i, 'description', e.target.value)} placeholder="Key responsibilities and achievements..." rows={2} style={{ ...inputStyle, resize: 'vertical' }} /></div>
                  </div>
                ))}
              </div>
            </div>

            {/* Education */}
            <div className="card">
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1.25rem' }}>Education</h2>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '0.75rem' }}>
                <div><label style={labelStyle}>Degree / Diploma</label><input value={education.degree} onChange={e => setEducation(p => ({ ...p, degree: e.target.value }))} placeholder="Bachelor's in Computer Science" style={inputStyle} /></div>
                <div><label style={labelStyle}>Institution</label><input value={education.institution} onChange={e => setEducation(p => ({ ...p, institution: e.target.value }))} placeholder="University name" style={inputStyle} /></div>
                <div><label style={labelStyle}>Year</label><input value={education.year} onChange={e => setEducation(p => ({ ...p, year: e.target.value }))} placeholder="2020" style={inputStyle} /></div>
              </div>
            </div>

            {/* Skills */}
            <div className="card">
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1.25rem' }}>Skills</h2>
              <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.75rem' }}>
                <input value={skillInput} onChange={e => setSkillInput(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addSkill(skillInput); } }}
                  placeholder="Type a skill and press Enter" style={{ ...inputStyle, flex: 1 }} />
                <button onClick={() => addSkill(skillInput)} className="btn-primary" style={{ whiteSpace: 'nowrap' }}>Add</button>
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem', marginBottom: '0.75rem' }}>
                {skills.map(s => (
                  <span key={s} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', background: '#eff6ff', color: '#1d4ed8', borderRadius: '9999px', padding: '0.3rem 0.75rem', fontSize: '0.82rem', fontWeight: 600 }}>
                    {s}
                    <button onClick={() => setSkills(p => p.filter(x => x !== s))} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#1d4ed8', fontSize: '0.9rem', lineHeight: 1 }}>×</button>
                  </span>
                ))}
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
                {SKILL_SUGGESTIONS.filter(s => !skills.includes(s)).map(s => (
                  <button key={s} onClick={() => addSkill(s)} style={{ background: '#f3f4f6', color: '#374151', border: 'none', borderRadius: '9999px', padding: '0.25rem 0.7rem', fontSize: '0.78rem', fontWeight: 600, cursor: 'pointer' }}>+ {s}</button>
                ))}
              </div>
            </div>

            {/* Languages */}
            <div className="card">
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#111827', marginBottom: '1.25rem' }}>Languages</h2>
              <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.75rem' }}>
                <input value={langInput} onChange={e => setLangInput(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addLang(langInput); } }}
                  placeholder="e.g. Arabic, French, English" style={{ ...inputStyle, flex: 1 }} />
                <button onClick={() => addLang(langInput)} className="btn-primary" style={{ whiteSpace: 'nowrap' }}>Add</button>
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
                {languages.map(l => (
                  <span key={l} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', background: '#f0fdf4', color: '#065f46', borderRadius: '9999px', padding: '0.3rem 0.75rem', fontSize: '0.82rem', fontWeight: 600 }}>
                    {l}
                    <button onClick={() => setLanguages(p => p.filter(x => x !== l))} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#065f46', fontSize: '0.9rem', lineHeight: 1 }}>×</button>
                  </span>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center' }}>
              <button className="btn-primary" onClick={handleSaveDownload}>⬇ Save & Download CV</button>
              <button onClick={handleSave} style={{ padding: '0.65rem 1.5rem', borderRadius: '8px', border: '1.5px solid #2563eb', background: 'white', color: '#2563eb', fontWeight: 600, fontSize: '0.9rem', cursor: 'pointer' }}>
                Save Profile
              </button>
              {saved && <span style={{ color: '#10b981', fontWeight: 600, fontSize: '0.875rem' }}>✓ Profile saved successfully</span>}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
